version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = ["**.feature"]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = ["resources/scripts/**.json", "resources/scripts/workflows/Workflow Examples Project/**.xml", "resources/scripts/workflows/Workflow Examples Project/**.xsl", "resources/scripts/**.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "CC0-1.0"