version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = [
	"src/main/resources/cases/*.cases",
	"src/main/resources/placeholders/*.json",
	"src/main/resources/workflows/**.expected"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "CC0-1.0"