version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = "contexts.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "EPL-1.0"