version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = ["src/main/assembly/**", "META-INF/services/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = ["**README.txt", "src/main/resources/*.properties", "src/main/resources/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "CC0-1.0"