version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = "maven/coreParent.pom"
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "EPL-1.0"
SPDX-FileComment = "preliminary"

[[annotations]]
path = "maven/utils/*.bat"
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "EPL-1.0"
SPDX-FileComment = "preliminary"