version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = "root_files/integration/tools/templates/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "CC0-1.0"