version = 1
SPDX-PackageName = "Remote Component Environment (RCE)"
SPDX-PackageDownloadLocation = "https://rcenvironment.de/"

[[annotations]]
path = ["src/test/resources/**.json", "src/test/resources/workflows_manual/files/CPACSToolIntegration/**.xml", "src/test/resources/workflows_manual/files/ToolIntegration/*.py", "src/test/resources/**readme"]
precedence = "aggregate"
SPDX-FileCopyrightText = "DLR"
SPDX-License-Identifier = "CC0-1.0"